# Startup Profit Predictions With Python Programing

## Import necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


## Import the dataset

In [2]:
dataset = pd.read_csv('50_Startups.csv')

In [3]:
# Examine the dataset

print(dataset.head(4))

   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99


In [4]:
# sepratting the independent columns

X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

## Encoding the categorical columns: the 'State column'

In [5]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

transformer = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [3])], remainder = "passthrough") 
new_X = np.array(transformer.fit_transform(X))

# connfirm the new change

print(new_X[:4])

[[0.0 0.0 1.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 144372.41 118671.85 383199.62]]


## Splitting the dataset into the training set and the test set

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(new_X, y, test_size = 0.2, random_state =0 )

In [7]:
print(X_train.shape, X_test.shape)

(40, 6) (10, 6)


## Training the X_train on a linear regression model

In [8]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()

regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

## Making prediction on the X_test

In [9]:
y_pred = regressor.predict(X_test)

In [10]:
# Comparing the predictions

np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[103015.2  103282.38]
 [132582.28 144259.4 ]
 [132447.74 146121.95]
 [ 71976.1   77798.83]
 [178537.48 191050.39]
 [116161.24 105008.31]
 [ 67851.69  81229.06]
 [ 98791.73  97483.56]
 [113969.44 110352.25]
 [167921.07 166187.94]]
